- hosts: web
  become: yes
  tasks:
    - name: Create ansible-worker user
      user:
        name: ansible-worker
        shell: /bin/bash
        state: present
      tags:
        - create_user

    - name: Install packages
      apt:
        name:
          - git
          - nginx
        state: present
        update_cache: yes
      tags:
        - install_packages

    - name: Create .ssh directory for ansible-worker
      file:
        path: /home/ansible-worker/.ssh
        state: directory
        owner: ansible-worker
        group: ansible-worker
        mode: '0700'
      tags:
        - setup_ssh

    - name: Copy SSH private key
      copy:
        src: ssh_keys/id_rsa
        dest: /home/ansible-worker/.ssh/id_rsa
        owner: ansible-worker
        group: ansible-worker
        mode: '0600'
      tags:
        - setup_ssh

    - name: Copy SSH public key
      copy:
        src: ssh_keys/id_rsa.pub
        dest: /home/ansible-worker/.ssh/id_rsa.pub
        owner: ansible-worker
        group: ansible-worker
        mode: '0644'
      tags:
        - setup_ssh

    - name: Remove existing www directory if it exists
      file:
        path: /home/ansible-worker/www
        state: absent
        force: yes
      tags:
        - clone_repo
    
    - name: Create www directory for repo
      file:
        path: /home/ansible-worker/www
        state: directory
        owner: ansible-worker
        group: ansible-worker
        mode: '0755'
      tags:
        - clone_repo

    - name: Create stud-template directory
      file:
        path: /home/ansible-worker/www/stud-template
        state: directory
        owner: ansible-worker
        group: ansible-worker
        mode: '0755'
      tags:
        - clone_repo

    - name: Add exception for dubious ownership in Git repository
      command: git config --global --add safe.directory /home/ansible-worker/www/stud-template
      tags:
        - clone_repo

    - name: Clone repo
      git:
        repo: 'git@github.com:iphilka/stud-template.git'
        dest: /home/ansible-worker/www/stud-template
        version: HEAD
        key_file: /home/ansible-worker/.ssh/id_rsa
      tags:
        - clone_repo

    - name: Create index.html from template
      template:
        src: templates/index.html.j2
        dest: /home/ansible-worker/www/stud-template/index.html
        owner: ansible-worker
        group: ansible-worker
        mode: '0644'
      tags:
        - create_index

    - name: Set permissions for www-data user
      file:
        path: /home/ansible-worker/
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes
      tags:
        - configure_nginx

    - name: Change ownership of index.html
      file:
        path: /home/ansible-worker/www/stud-template/index.html
        owner: www-data
        group: www-data
      tags:
        - configure_nginx

    - name: Change permissions of index.html
      file:
        path: /home/ansible-worker/www/stud-template/index.html
        mode: '0755'
      tags:
        - configure_nginx

    - name: Configure Nginx
      copy:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/ansible.iphilka.ru.conf
      tags:
        - configure_nginx

    - name: Create symlink for Nginx config
      file:
        src: /etc/nginx/sites-available/ansible.iphilka.ru.conf
        dest: /etc/nginx/sites-enabled/ansible.iphilka.ru.conf
        state: link
      tags:
        - configure_nginx

    - name: Remove default Nginx config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      tags:
        - configure_nginx
  
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
      tags:
        - configure_nginx
